export const subjects = {
    "Arts": [
        "Art History",
        "Band",
        "Choir",
        "Dance",
        "Drama",
        "Drawing",
        "Film Production",
        "Graphic Design",
        "Music",
        "Music Theory",
        "Painting",
        "Photography",
        "Sculpture",
        "Theatre Arts",
        "Visual Arts"
    ],
    "Business & Economics": [
        "Accounting",
        "Business",
        "Business Law",
        "Economics",
        "Entrepreneurship",
        "Finance",
        "Marketing",
        "Personal Finance"
    ],
    "Computer Science & Information Technology": [
        "AP Computer Science A",
        "AP Computer Science Principles",
        "Coding",
        "Computer Applications",
        "Computer Programming",
        "Computer Science",
        "Cybersecurity",
        "Digital Media",
        "Game Design",
        "Information Technology",
        "Web Design"
    ],
    "English & Language Arts": [
        "AP English Language and Composition",
        "AP English Literature and Composition",
        "Communication Skills",
        "Creative Writing",
        "Debate",
        "English",
        "English Literature",
        "Journalism",
        "Literature",
        "Public Speaking",
        "Speech",
        "Technical Writing"
    ],
    "Family & Consumer Sciences": [
        "Child Development",
        "Culinary Arts",
        "Fashion Design",
        "Family Studies",
        "Home Economics",
        "Interior Design",
        "Nutrition",
        "Textiles"
    ],
    "Health & Physical Education": [
        "Anatomy",
        "CPR Training",
        "First Aid",
        "Health",
        "Physical Education",
        "Sports Medicine"
    ],
    "Humanities & Social Sciences": [
        "AP European History",
        "AP Human Geography",
        "AP Macroeconomics",
        "AP Microeconomics",
        "AP Psychology",
        "AP United States Government and Politics",
        "AP United States History",
        "AP World History",
        "Anthropology",
        "Civics",
        "Criminology",
        "Environmental Systems and Societies (IB)",
        "Geography",
        "Global Politics",
        "History",
        "Human Geography",
        "Law",
        "Philosophy",
        "Political Science",
        "Psychology",
        "Sociology",
        "World History"
    ],
    "Languages (Foreign & Classical)": [
        "Arabic",
        "Chinese",
        "French",
        "German",
        "Greek (Classical)",
        "Hebrew",
        "Italian",
        "Japanese",
        "Latin",
        "Russian",
        "Spanish"
    ],
    "Mathematics": [
        "Algebra I",
        "Algebra II",
        "AP Calculus AB",
        "AP Calculus BC",
        "AP Statistics",
        "Calculus",
        "Geometry",
        "Pre-Calculus",
        "Statistics",
        "Trigonometry"
    ],
    "Sciences": [
        "AP Biology",
        "AP Chemistry",
        "AP Environmental Science",
        "AP Physics 1: Algebra-Based",
        "AP Physics 2: Algebra-Based",
        "AP Physics C: Electricity and Magnetism",
        "AP Physics C: Mechanics",
        "Biology",
        "Chemistry",
        "Earth Science",
        "Environmental Science",
        "Forensic Science",
        "Physics"
    ],
    "Technical & Vocational Studies": [
        "Agricultural Science",
        "Auto Mechanics",
        "Carpentry",
        "Cosmetology",
        "Culinary Arts",
        "Design and Technology",
        "Digital Technology",
        "Drafting",
        "Electrical Technology",
        "Engineering",
        "Graphic Communications",
        "Health Occupations",
        "Horticulture",
        "Industrial Technology",
        "Information Technology",
        "Journalism",
        "Plumbing",
        "Robotics",
        "Welding"
    ],
    "Life Skills & Other Electives": [
        "Career Exploration",
        "Community Service",
        "Driver's Education",
        "Financial Management",
        "Leadership",
        "Life Skills",
        "Study Skills"
    ],
    "Capstone & Advanced Programs": [
        "AP Capstone",
        "AP Research",
        "AP Seminar",
        "Extended Essay (IB)",
        "International Baccalaureate (IB) Diploma Programme",
        "Theory of Knowledge (IB)"
    ]
};
